/*
 * Copyright (c) 2024 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export class DigitalScrollConstants {
  /**
   * Number length.
   */
  public static readonly NUMBER_LENGTH: number = 7;
  /**
   * Duration time.
   */
  public static readonly DURATION_TIME: number = 200;
  /**
   * Millennial length.
   */
  public static readonly MILLENNIAL_LENGTH: number = 3;
  /**
   * Item space.
   */
  public static readonly ITEM_SPACE: number = 12;
  /**
   * Item height.
   */
  public static readonly ITEM_HEIGHT: number = 26;
  /**
   * Text space.
   */
  public static readonly TEXT_SPACE: number = 2;
  /**
   * Time out.
   */
  public static readonly TIME_OUT: number = 1000;
  /**
   * Text translate.
   */
  public static readonly TEXT_TRANSLATE: number = 0;
}