/*
 * Copyright (c) 2026 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { ItemInfo } from './ItemInfo';

export const itemData: ItemInfo[] = [
  {
    index: 0,
    title: $r('app.string.no_image_recommendation')
  },
  {
    index: 1,
    title: $r('app.string.Service_specific_recommendations')
  },
  {
    index: 2,
    title: $r('app.string.text_recommendations')
  }
]