/*
 * Copyright (c) 2026 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export default class CommonConstants {
  /**
   * TAG.
   * */
  public static readonly KEY_PREFIX: string = 'readerkitsamplecodearktssample';

  /**
   * isDensityChange.
   * */
  public static readonly KEY_STATUS_BAR_HEIGHT: string = CommonConstants.KEY_PREFIX + 'isDensityChange';

  /**
   * navigationAiBarHeight.
   * */
  public static readonly KEY_NAVIGATION_AI_BAR_HEIGHT: string = CommonConstants.KEY_PREFIX + 'navigationAiBarHeight';

  /**
   * Paf.TopHeight.
   * */
  public static readonly KEY_PAF_TOP_HEIGHT: string = CommonConstants.KEY_PREFIX + 'Paf.TopHeight';

  /**
   * windowWidth.
   * */
  public static readonly KEY_WINDOW_WIDTH: string = CommonConstants.KEY_PREFIX + 'windowWidth';

  /**
   * windowHeight.
   * */
  public static readonly KEY_WINDOW_HEIGHT: string = CommonConstants.KEY_PREFIX + 'windowHeight';

  /**
   * NavigationBarHeight.
   * */
  public static readonly KEY_NAVIGATION_BAR_HEIGHT: string = CommonConstants.KEY_PREFIX + 'NavigationBarHeight';

  /**
   * NavigationBarHeight.
   * */
  public static readonly KEY_GRID_TAB_PRO_ENABLE_AVOID_AREA_LISTENER: string = CommonConstants.KEY_PREFIX + 'Grid.tabPro.enableAvoidAreaListener';

  /**
   * CurrentBreakpoint.
   * */
  public static readonly KEY_CURRENT_BREAKPOINT: string = CommonConstants.KEY_PREFIX + 'currentBreakpoint';

  /**
   * isWide.
   * */
  public static readonly KEY_IS_WIDE: string = CommonConstants.KEY_PREFIX + 'isWide';

  /**
   * colorMode.
   * */
  public static readonly KEY_COLOR_MODE: string = CommonConstants.KEY_PREFIX + 'colorMode';

  /**
   * isDensityChange.
   * */
  public static readonly KEY_IS_DENSITY_CHANGE: string = CommonConstants.KEY_PREFIX + 'isDensityChange';

  /**
   * filePath.
   * */
  public static readonly KEY_FILE_PATH: string = CommonConstants.KEY_PREFIX + 'filePath';

  /**
   * filePath.
   * */
  public static readonly KEY_CURRENT_DATA: string = CommonConstants.KEY_PREFIX + 'currentData';
}