/*
 * Copyright (c) 2026 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export class ImmersionConstants {
  public static readonly VIDEO_ASPECT_RATIO_9_16 = 9 / 16;
  public static readonly VIDEO_ASPECT_RATIO_9_16o1 = 9 / 16.1;
  public static readonly VIDEO_ASPECT_RATIO_9_15o9 = 9 / 15.9;
  public static readonly VIDEO_STRETCH_ASPECT_RATIO_17o8_16 = 17.8 / 16;
  public static readonly WINDOW_ASPECT_RATIO_9_9 = 9 / 9;
  public static readonly WINDOW_ASPECT_RATIO_9_10o8 = 9 / 10.8;
  public static readonly WINDOW_ASPECT_RATIO_9_14o4 = 9 / 14.4;
  public static readonly WINDOW_ASPECT_RATIO_9_16 = 9 / 16;
  public static readonly WINDOW_ASPECT_RATIO_9_17o8 = 9 / 17.8;
  public static readonly WINDOW_ASPECT_RATIO_9_18 = 9 / 18;
  public static readonly WINDOW_ASPECT_RATIO_9_20 = 9 / 20;
}