/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export class ColorConstants {
  public static readonly TAB_TEXT_WHITE: string = '#FFFFFF';

  public static readonly BUTTON_BG_LIGHT: string = '#66FFFFFF';

  public static readonly ICON_LIGHT: string = '#E5FFFFFF';
  public static readonly BORDER_DEFAULT: string = '#DDDDDD';

  public static readonly ACCENT_PURPLE: string = '#954CD9';
  public static readonly ACCENT_STAR_YELLOW: string = '#FFCA28';
  public static readonly ACCENT_STAR_INACTIVE: string = '#DDDDDD';

  public static readonly EXERCISE_ORANGE: string = '#FB6522';
  public static readonly CLOVER_PURPLE: string = '#8981F7';
  public static readonly CLOVER_ORANGE: string = '#FF7500';
  public static readonly CLOVER_BLUE: string = '#00A5AD';
  public static readonly TASK_COMPLETED_BG: string = '#1AFB6522';
  public static readonly TASK_COMPLETED_ICON: string = '#F56522';

  public static readonly SHADOW_CARD: string = 'rgba(0,0,0,0.05)';

  public static readonly LYRIC_STAR: string = '#18BBFC';
  public static readonly LYRIC_CURRENT: string = '#FFFFFF';
  public static readonly LYRIC_NORMAL: string = '#99ffffff';
}

export class SleepStageColors {
  public static readonly DEEP: string = '#6a1b9a';
  public static readonly LIGHT: string = '#ab47bc';
  public static readonly REM: string = '#ff7043';
  public static readonly AWAKE: string = '#ffca28';
}