/*
 * Copyright (c) 2026 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * Common constants for all features.
 */
export class CommonConstants {
  /**
   * Full percent.
   */
  public static readonly FULL_PERCENT: string = '100%';
  /**
   * Seventy-five percent.
   */
  public static readonly SEVENTY_FIVE_PERCENT: string = '75%';
  /**
   * Half percent.
   */
  public static readonly HALF_PERCENT: string = '50%';
  /**
   * At SYumbol.
   */
  public static readonly AT_SYMBOL: string = '@';
  /**
   * Middle Dot Symbol.
   */
  public static readonly MIDDLE_DOT_SYMBOL: string = '·';
  /**
   * Initialized state of avPlayer
   */
  public static readonly AV_PLAYER_IDLE_STATE: string = 'idle';
  /**
   * Initialized state of avPlayer
   */
  public static readonly AV_PLAYER_INITIALIZED_STATE: string = 'initialized';
  /**
   * Prepared state of avPlayer
   */
  public static readonly AV_PLAYER_PREPARED_STATE: string = 'prepared';
  /**
   * Playing state of avPlayer
   */
  public static readonly AV_PLAYER_PLAYING_STATE: string = 'playing';
  /**
   * Pause state of avPlayer
   */
  public static readonly AV_PLAYER_PAUSED_STATE: string = 'paused';
  /**
   * Completed state of avPlayer
   */
  public static readonly AV_PLAYER_COMPLETED_STATE: string = 'completed';
  /**
   * Error state of avPlayer
   */
  public static readonly AV_PLAYER_ERROR_STATE: string = 'error';
}