

export class CommonConstants {
  /**
   * Initial height of the backup search box.
   */
  public static readonly SEARCH_HEIGHT_RAW: number = 100;

  /**
   * Backup height of quick capture icon area 2.
   */
  public static readonly HEIGHT_LIST_2_RAW: number = 100;

  /**
   * Default maximum spacing of icon list 3.
   */
  public static readonly MAX_MARGIN_SPACE: number = 25;

  /**
   * Default minimum spacing of icon list 3.
   */
  public static readonly MIN_MARGIN_SPACE: number = 12;

  /**
   * Calculates the transparency of icon list 1.
   */
  public static readonly ICON_LIST_1_RAW: number = 100;

  /**
   * Calculates the transparency of icon list 2.
   */
  public static readonly ICON_LIST_2_RAW: number = 120;

  /**
   * Calculates the transparency of icon list 3.
   */
  public static readonly ICON_LIST_3_RAW: number = 140;

  /**
   * Occupied height.
   */
  public static readonly USED_SPACE: number = 110;

  /**
   * Product list column margin.
   */
  public static readonly MARGIN_TOP: number = 200;

  /**
   * Spacing between icons.
   */
  public static readonly ICON_VIEW_SPACE: number = 10;

  /**
   * Number of columns in list 1.
   */
  public static readonly ICON_LIST_COLUMNS_1: number = 4;

  /**
   * Number of columns in list 2.
   */
  public static readonly ICON_LIST_COLUMNS_2: number = 5;

  /**
   * Spacing between column subcomponents.
   */
  public static readonly COLUMN_SPACE: number = 5;

  /**
   * Price control offset.
   */
  public static readonly OFFSET: number = -4;

  /**
   * WaterFlow component vertical spacing.
   */
  public static readonly COLUMNS_GAP: number = 12;

  /**
   * Horizontal spacing between WaterFlow components.
   */
  public static readonly ROWS_GAP: number = 12;

  /**
   * 100 percent.
   */
  public static readonly FULL_PERCENT: string = '100%';
  /**
   * AppStorage key prefix.
   */
  public static readonly KEY_PREFIX: string = 'componentStack';
}