/*
 * Copyright (c) 2026 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

const KEY_PREFIX = 'multiticketclass';

export const KEY_IS_SPLIT_SCREEN = KEY_PREFIX + 'isSplitScreen';

export const KEY_IS_HIDE_SPLIT_SCREEN = KEY_PREFIX + 'isHideSplitScreen';

export const KEY_SYSTEM_COLOR_MODE = KEY_PREFIX + 'systemColorMode';

export const KEY_CURRENT_COLOR_MODE = KEY_PREFIX + 'currentColorMode';

export const KEY_WINDOW_UTIL = KEY_PREFIX + 'windowUtil';

export const KEY_RESOURCE_MANAGER = KEY_PREFIX + 'resourceManager';

export const KEY_MAIN_WINDOW_INFO = KEY_PREFIX + 'mainWindowInfo';

export const KEY_SHARES_HELD_NUMBER = KEY_PREFIX + 'sharesHeldNumber';