/*
 * Copyright (c) 2026 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export class AccountConstants {
  /**
   * Product amount.
   */
  public static readonly TOTAL_AMOUNT: string = '999999.99';
  public static readonly YESTERDAY_INCOME: string = '+333.33';
  public static readonly DEMAND_AMOUNT: string = '88888.88';
  public static readonly DEMAND_DEPOSIT: string = '33333.33';
  public static readonly DEMAND_WEALTH: string = '55555.55';
  public static readonly INVESTMENT_AMOUNT: string = '155555.54';
  public static readonly LIABILITY_AMOUNT: string = '55555.55';
  public static readonly INVESTMENT_WEALTH: string = '88888.88';
  public static readonly INVESTMENT_POSITION_INCOME: string = '66.66';
  public static readonly INVESTMENT_POSITION_AMOUNT: string = '66666.66';
  public static readonly INVESTMENT_DATE: string = '2023-11-23';
  public static readonly INVESTMENT_FUND: string = '66666.66';
  public static readonly INVESTMENT_YESTERDAY_INCOME_FUND: string = '-66.66';
  public static readonly INVESTMENT_POSITION_INCOME_FUND: string = '666.66';
  public static readonly INVESTMENT_POSITION_AMOUNT_FUND: string = '66666.66';
  public static readonly LIABILITY_AVAILABLE_LIMIT: string = '500000.00';
}
