/*
 * Copyright (c) 2024 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * Common constants for all features.
 */
export default class Constants {
  /**
   * Default color of the Circle component.
   */
  public static readonly COLOR_NORMAL: string = '#E5000000';
  /**
   * Default Background Color.
   */
  public static readonly COLOR_TRANSPARENT: string = '#00000000';
  /**
   * Display percentage of the Circle component.
   */
  public static readonly PERCENTAGE_STR: string = '%';
  /**
   * Maximum Percentage.
   */
  public static readonly LAYOUT_MAX_PERCENT: string = '100%';
  /**
   * Communication Color.
   */
  public static readonly OHOS_ID_COLOR_PALETTE4: string = '#64BB5C';
  /**
   * Progress Step.
   */
  public static readonly PROGRESS_STEP: number = 0.5;
  /**
   * Size of the Circle component.
   */
  public static readonly DIAMETER: number = 200;
  /**
   * Big Diameter.
   */
  public static readonly BIG_DIAMETER: number = 220;
  /**
   * Full Progress.
   */
  public static readonly FULL_PROGRESS: number = 100;
  /**
   * Zero Progress.
   */
  public static readonly ZERO_PROGRESS: number = 0;
  /**
   * Unit One.
   */
  public static readonly UNIT_ONE: number = 1;
  /**
   * Percent Rate.
   */
  public static readonly PERCENT_RATE: number = 100.0;
  /**
   * Progress Change Interval.
   */
  public static readonly PROGRESS_CHANGE_INTERVAL: number = 10;
  /**
   * Initialize 0.
   */
  public static readonly ZERO: number = 0;
}