/*
 * Copyright (c) 2024 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export class Constants {
  /*
   * Picture_grid_margin.
   */
  public static readonly PICTURE_GRID_MARGIN: number[] = [16, 24, 32];
  /*
   * Static icon size.
   */
  public static STATIC_ICON_SIZE = 24;
  /*
   * Big icon size.
   */
  public static BIG_ICON_SIZE = 36;
  /*
   * Button size.
   */
  public static BUTTON_SIZE = 40;
  /*
   * Button size.
   */
  public static ASPECT_RATIO_16_9 = 16 / 9;
  /*
   * Full size.
   */
  public static FULL_SIZE = '100%';
  /*
   * AppStorage key prefix.
   */
  public static readonly KEY_PREFIX: string = 'fluentblog';
  /*
   * Video name.
   */
  public static readonly VIDEO_NAME: string = 'videoTest.mp4';
  /*
   * SM video ratio.
   */
  public static SM_RATIO = '100%';
  /*
   * MD video ratio.
   */
  public static MD_RATIO = '70%';
  /*
   * LG video ratio.
   */
  public static LG_RATIO = '60%';
  /*
   * SM video size.
   */
  public static SM_SIZE = 240;
  /*
   * MD video size.
   */
  public static MD_SIZE = 280;
  /*
   * LG video size.
   */
  public static LG_SIZE = 480;
}