/*
 * Copyright (c) 2026 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export class HomeConstants {
  public static readonly FUNCTION_SIZE_JUDGE: number = 6;
  public static readonly LIST_ITEM_SPACE: number = 5;
  public static readonly FUNCTION_ROW_WIDTH: string = '90%';
  public static readonly DIVIDER_STROKE_WIDTH: number = 1;
  public static readonly SWIPER_ITEM_SPACE: number = 12;
  public static readonly SEARCHBAR_WIDTH: string = '100% - 48';
  public static readonly TEXT_WIDTH: string = '70%';
}
