/*
 * Copyright (c) 2024 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
export class CommonConstants {
  /**
   * Full percent.
   */
  public static readonly FULL_PERCENT: string = '100%';
  /**
   * Font weight 500.
   */
  public static readonly FONT_WEIGHT_500: number = 500;
  /**
   * Swiper height.
   */
  public static readonly SWIPER_HEIGHT: number = 367;
  /**
   * Swiper margin.
   */
  public static readonly SWIPER_MARGIN: number = 172;
  /**
   * Swiper item space.
   */
  public static readonly SWIPER_ITEM_SPACE: number = 12;
  /**
   * Graphic aspect ratio.
   */
  public static readonly GRAPHIC_ASPECT_RATIO: number = 0.74;
  /**
   * Default delay.
   */
  public static readonly DEFAULT_DURATION: number = 500;
  /**
   * Slip coefficient.
   */
  public static readonly HEIGHT_COEFFICIENTS: number = 0.2;
  /**
   * Slip coefficient.
   */
  public static readonly MARGIN_COEFFICIENTS: number = 0.1;
  /**
   * Word weight 700.
   */
  public static readonly FONT_WEIGHT_700: number = 700;
  /**
   * Word weight 400.
   */
  public static readonly FONT_WEIGHT_400: number = 400;
  /**
   * Word weight 600.
   */
  public static readonly FONT_WEIGHT_600: number = 600;
  /**
   * Dish lg index.
   */
  public static readonly DISH_LG_INDEX: number = 16;
  /**
   * Dish index.
   */
  public static readonly DISH_INDEX: number = 4;
  /**
   * Gradient color angle.
   */
  public static readonly ANGLE_IMAGE: number = 180;
  /**
   * Gradient color index.
   */
  public static readonly LINEAR_GRADIENT_INDEX: number = 0.16;
  /**
   * Grid column span list.
   */
  public static readonly OFFSET_ARRAY: number[] = [3, 10, 20, 30, 40, 50];
  /**
   * Attribute adaptation.
   */
  public static readonly SELF_ADAPTING: string = 'auto';
  /**
   * NavDestination default route.
   */
  public static readonly DEFAULT_ROUTE: string = 'default';
  /**
   * Shared element transition id.
   */
  public static readonly GRAPHIC_GEOMETRY_ID: string = 'graphic_picture_';
  /**
   * Image component id.
   */
  public static readonly GRAPHIC_IMAGE_ID: string = 'image2';
  /**
   * Home page route.
   */
  public static readonly PAGE_ROUTER_INDEX: string = 'button';
  /**
   * Default spacing.
   */
  public static readonly DEFAULT_SPACE: string = '12vp';
  /**
   * Fifty percent.
   */
  public static readonly FIFTY_PERCENT: Percentage = '50%';
  /**
   * Forty percent.
   */
  public static readonly FORTY_PERCENT: Percentage = '40%';
  /**
   * Thirty-three percent..
   */
  public static readonly THIRTY_THREE_PERCENT: string = '33.33%';
  /**
   * Fifty percent.
   */
  public static readonly FIFTY_PERCENT_STRING: string = '50%';
  /**
   * Forty percent.
   */
  public static readonly FORTY_PERCENT_STRING: string = '40%';
  /**
   * Thirty-seven point five percent.
   */
  public static readonly THIRTY_SEVEN_PERCENT: string = '37.5%';
  /**
   * Sixty percent.
   */
  public static readonly SIXTY_PERCENT: string = '60%';
  /**
   * Seventy percent.
   */
  public static readonly SEVENTY_PERCENT: string = '70%';
  /**
   * Ninety percent.
   */
  public static readonly NINETY_PERCENT: string = '90%';
  /**
   * Eighty-three thirty-three percent.
   */
  public static readonly EIGHTY_THREE_PERCENT: string = '83.33%';
  /**
   * Gradient start color.
   */
  public static readonly LINEAR_GRADIENT_FIRST: string = 'rgba(0,0,0,0)';
  /**
   * Gradient color.
   */
  public static readonly LINEAR_GRADIENT_SECOND: string = 'rgba(0,0,0,0.68)';
  /**
   * Currency symbol.
   */
  public static readonly CURRENCY_SYMBOL: string = '¥';
  /**
   * Swiper height.
   */
  public static readonly TEXT_SWIPER_HEIGHT: string = '480vp';
  /**
   * Column space.
   */
  public static readonly COLUMN_SPACE: string = '16vp';
  /**
   * Column space.
   */
  public static readonly COLUMN_SPACE_LIVING: string = '12vp';
  /**
   * Column space.
   */
  public static readonly COLUMN_SPACE_HOME: string = '8vp';
  /**
   * Font family HarmonyHeiTi.
   */
  public static readonly FONT_FAMILY_BLACK: string = 'HarmonyHeiTi';
  /**
   * Animate duration.
   */
  public static readonly ANIMATE_DURATION: number = 500;
  /**
   * Icon image position.
   */
  public static readonly ICON_IMAGE_POSITION: number = 8;
  public static readonly LIFE_PREFIX: string = 'convenient_life_';
}