/*
 * Copyright (c) 2024 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * Constants for main content area.
 */
export class ContentConstants {
  /**
   * The max lines of play all area is 1.
   */
  public static readonly PLAY_ALL_MAX_LINES: number = 1;
  /**
   * Value of lanes is 2.
   */
  public static readonly COL_TWO: number = 2;
  /**
   * Value of lanes is 1.
   */
  public static readonly COL_ONE: number = 1;
}