/*
 * Copyright (c) 2024 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * Constants for player area.
 */
export class PlayerConstants {
  /**
   * The value of font weight.
   */
  public static readonly FONT_WEIGHT_700: number = 700;
  /**
   * The value of font weight.
   */
  public static readonly FONT_WEIGHT_500: number = 500;
  /**
   * The value of font family.
   */
  public static readonly FONT_FAMILY_BLACK: string = 'HarmonyHeiTi';
  /**
   * The value of font family.
   */
  public static readonly FONT_FAMILY_BOLD: string = 'HarmonyHeiTi-Bold';
  /**
   * The value of font family.
   */
  public static readonly FONT_FAMILY_MEDIUM: string = 'HarmonyHeiTi-Medium';
  /**
   * The value of encoding.
   */
  public static readonly ENCODING: string = 'utf-8';
  /**
   * The value of back ground image width and height.
   */
  public static readonly BACK_IMAGE: string = '120%';
  /**
   * Set the image blur level.
   */
  public static readonly IMAGE_BLUR: number = 15;
}