/*
 * Copyright (c) 2026 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export class TvConstants {
  /**
   * Page name for video.
   */
  public static readonly PAGE_NAME_FOR_VIDEO: string = 'MultiVideoDetail';
  /**
   * Bottom tab index for search page.
   */
  public static readonly SEARCH_BOTTOM_INDEX: number = 2;
  /**
   * Bottom tab index for home page.
   */
  public static readonly HOME_BOTTOM_INDEX: number = 3;
  /**
   * Count of icon tabs displayed before text tabs.
   */
  public static readonly HEADER_ICON_TAB_COUNT: number = 3;
}
