/*
 * Copyright (c) 2026 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export default class CommonConstants {
  /**
   * Key prefix.
   * */
  public static readonly KEY_PREFIX: string = 'icon_main_color';
  /**
   * List space.
   * */
  public static readonly LIST_SPACE: number = 12;
  /**
   * Opacity of text name font.
   * */
  public static readonly TEXT_NAME_FONT_OPACITY: number = 0.9;
  /**
   * Opacity of text name description font.
   * */
  public static readonly TEXT_NAME_DESCRIPTION_FONT_OPACITY: number = 0.6;
  /**
   * Width of pixelmap size.
   * */
  public static readonly PIXEL_MAP_SIZE_WIDTH: number = 40;
  /**
   * Height of pixelmap size.
   * */
  public static readonly PIXEL_MAP_SIZE_HEIGHT: number = 40;
  public static readonly MODIFY_SV_COLOR_SATURATION_12: number = 0.12;
  public static readonly MODIFY_SV_COLOR_SATURATION_8: number = 0.08;
  public static readonly MODIFY_SV_COLOR_SATURATION_10: number = 0.1;
  public static readonly MODIFY_SV_COLOR_VALUE_93: number = 0.93;
  public static readonly MODIFY_SV_COLOR_VALUE_91: number = 0.91;
  public static readonly MODIFY_SV_COLOR_HUE_60: number = 60;
  public static readonly MODIFY_SV_COLOR_HUE_190: number = 190;
  public static readonly MODIFY_SV_COLOR_HUE_270: number = 270;
  public static readonly RGB_WIDTH: number = 40;
  public static readonly RGB_HEIGHT: number = 40;
  public static readonly RGB_BIT_ONE_PIXEL: number = 4;
  public static readonly MAX_RGB_VALUE: number = 255;
  public static readonly BIT_16: number = 16;
  public static readonly BIT_24: number = 24;
  public static readonly BIT_8: number = 8;
  public static readonly HSV_TO_RGB_60: number = 60;
  public static readonly HSV_TO_RGB_6: number = 6;
  public static readonly HSV_TO_RGB_REMAINDER_1: number = 1;
  public static readonly HSV_TO_RGB_REMAINDER_2: number = 2;
  public static readonly HSV_TO_RGB_REMAINDER_3: number = 3;
  public static readonly HSV_TO_RGB_REMAINDER_4: number = 4;
  public static readonly HSV_TO_RGB_REMAINDER_5: number = 5;
  public static readonly RGB_TO_HSV_60: number = 60;
  public static readonly RGB_TO_HSV_360: number = 360;
  public static readonly RGB_TO_HSV_2: number = 2;
  public static readonly RGB_TO_HSV_4: number = 4;
}